[package]
name = "jp"
version = "0.0.1"
authors = ["Kevin Lanni <therealklanni@gmail.com>"]

[dependencies]
serde_json = "*"

[dependencies.clap]
version = "2.31.2"
features = ["suggestions", "color"]
